version: '3'

services:
  web:
    build: .
    container_name: my_web_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo_data:/data/db

  socket_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socket_server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
